name: Build APK 
 
on: 
  workflow_dispatch: 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 
 
      - name: Grant execute permission to Gradle 
        run: chmod +x ./VoiceDenoiserApp/gradlew 
 
      - name: Set up JDK 
        uses: actions/setup-java@v3 
        with: 
          distribution: temurin 
          java-version: '17' 
 
      - name: Build the APK 
        run: ./gradlew assembleRelease 
        working-directory: VoiceDenoiserApp 
 
      - name: Upload APK artifact 
        uses: actions/upload-artifact@v4 
        with: 
          name: VoiceDenoiserApp 
          path: VoiceDenoiserApp/app/build/outputs/apk/release/app-release.apk
