name: Build APK 
 
on: 
  workflow_dispatch: 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v3 
 
      - name: Replace gradlew with valid script 
        run: | 
          echo '#!/bin/sh' > ./VoiceDenoiserApp/gradlew 
          echo 'DIRNAME=$(dirname "$0")' >> ./VoiceDenoiserApp/gradlew 
          echo 'exec java -jar "$DIRNAME/gradle/wrapper/gradle-wrapper.jar" "$@"' >> 
./VoiceDenoiserApp/gradlew 
          chmod +x ./VoiceDenoiserApp/gradlew 
 
      - name: Fix gradle-wrapper.jar permissions 
        run: chmod 644 ./VoiceDenoiserApp/gradle/wrapper/gradle-wrapper.jar 
 
      - name: Setup JDK 17 
        uses: actions/setup-java@v3 
        with: 
          distribution: temurin 
          java-version: '17' 
 
      - name: Build APK 
        run: ./gradlew assembleRelease 
        working-directory: VoiceDenoiserApp 
 
      - name: Upload APK artifact 
        uses: actions/upload-artifact@v4 
        with: 
          name: VoiceDenoiserApp 
          path: VoiceDenoiserApp/app/build/outputs/apk/release/app-release.apk
