name: Build APK 
 
on: 
  workflow_dispatch: 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3 
 
      - name: Set up JDK 17 
        uses: actions/setup-java@v3 
        with: 
          distribution: temurin 
          java-version: '17' 
 
      - name: Install Gradle 
        run: | 
          sudo apt-get update 
          sudo apt-get install -y gradle 
 
      - name: Build APK 
        run: gradle assembleRelease 
        working-directory: . 
 
      - name: Upload APK 
        uses: actions/upload-artifact@v4 
        with: 
          name: AudioAnalyzApp 
          path: app/build/outputs/apk/release/app-release.apk
